package POJO;
// Generated Oct 1, 2021 11:35:14 AM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import DAO.DAOPelanggan;
import java.util.List;
import javax.faces.bean.ManagedBean;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Product generated by hbm2java
 */
@ManagedBean
public class Pelanggan  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String phone;
     private String date;
     private String seats;

    public List<Pelanggan> getAllRecords() {
        DAOPelanggan pelanggan = new DAOPelanggan();
        List<Pelanggan> listPelanggan = pelanggan.retrveTblpelanggan();
        return listPelanggan;
    }
    
    public String getById() {
        String idPelanggan = id.toString();
        DAOPelanggan pelanggan = new DAOPelanggan();
        List<Pelanggan> listPelanggan = pelanggan.getbyID(idPelanggan);
        try {
            if (listPelanggan != null) {
                nama = listPelanggan.get(0).nama;
                phone= listPelanggan.get(0).phone;
                date = listPelanggan.get(0).date;
                seats = listPelanggan.get(0).seats;
                return "admin";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "gagal";
    }
    
    public String savePelanggan() {
        DAOPelanggan pelanggan = new DAOPelanggan();
        pelanggan.addPelanggan(this);
        nama = "";
        phone = "";
        date = "";
        seats = "";
        return "index";
    }
    
    public String editPelanggan() {
        DAOPelanggan pelanggan = new DAOPelanggan();
        pelanggan.editUser(this);
        nama = "";
        phone = "";
        date = "";
        seats = "";
        return "index";
    }
    
    public String deletePelanggan() {
        DAOPelanggan pelanggan = new DAOPelanggan();
        pelanggan.deleteUser(id);
        nama = "";
        phone = "";
        date = "";
        seats = "";
        return "index";
    }
    public Pelanggan() {
    }

    public Pelanggan(String nama, String date, String seats, String phone) {
       this.nama = nama;
       this.date = date;
       this.seats = seats;
       this.phone = phone;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getSeats() {
        return seats;
    }

    public void setSeats(String seats) {
        this.seats = seats;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
   

}


