package POJO;
// Generated Oct 1, 2021 11:35:14 AM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Employees generated by hbm2java
 */
@ManagedBean
public class TblUser implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     
    public String save_user(){
        DAOLogin add = new DAOLogin();
        return add.add_user(this);
       }    
    public String login_user() {
        DAOLogin uDao = new DAOLogin();
        List<TblUser> us = uDao.getBy(username, password);
        try {
            if (us != null) {
                username = us.get(0).username;
                password = us.get(0).password;
                return "admin.xhtml";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "logingagal.xhtml";
    }

     
    public TblUser() {
    }

    public TblUser(String username, String password) {
       this.username = username;
       this.password = password;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
   


}


